name: Voice Crush
description: 'Elevate Your Voice, Crush the Noise.<br>Your Ultimate Noise-Be-Gone recording App.'
full_description: 'Tired of hunting for a quiet spot to record your voice messages? Fed up with noisy backgrounds sabotaging your audio recordings?<br><br>Look no further! Voice Crush is here to silence the chaos and ensure your voice shines through. With cutting-edge denoising AI technology, Voice Crush effortlessly sweeps away distracting background noise and echoes, ensuring your voice is crystal clear.<br><br>Confidently communicate with friends and colleagues even amidst barking dogs, vacuum cleaners, or construction chaos at home. And when you are on the go, have uninterrupted conversations in a car, coffee shop, or airport - wherever life takes you. Your voice will prevail, even in the most challenging acoustic environments.'
android: https://play.google.com/store/apps/details?id=com.studio9.voicecrush
iOS: https://apps.apple.com/us/app/voicecrush/id1670383196
#web: 
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
companies:
  - url: https://producthunt.com/posts/voice-crush
    image: producthunt.png