name: Scribbn
description: Convert your voice messages from WhatsApp and co. to text. See at a glance the emotions and key phrases to find out what is about.<br><br>Our hearts go out to all affected by this war who begin a whole new life away from home. That’s why, all Ukrainian voice notes are transcribed for free. So that being in contact with the ones you love the most is easier.
full_description: 'Have you ever been receiving voice messages and not being able to listen to it in peace? Now you can convert them to text and know in time what your friends are saying, even in situations where putting your phone to your ear is not an option such as at meetings, theaters, events etc. Scan information with your eyes at a pace faster than the sender&#39;s um&#39;s and uh&#39;s.<br><br>Scribbn&#39;s sophisticated AI extracts key phrases and emotions so that you can quickly find out what that voice message is about. After processing is finished the audio is not stored remotely with respect to your privacy. You can also easily search to find a specific voice message with some typing, meaning that you never have to scroll for hours through your conversations anymore.'
android: https://play.google.com/store/apps/details?id=com.technidoo.scribbn
iOS: https://apps.apple.com/us/app/id1585425122
#web: 
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
  - 5.png
#producthunt: https://producthunt.com/posts/scribbn
companies:
  - url: https://www.cuatro.com/futura/20220531/app-movil-revolucionarias-audio-nivel-polen_18_06612022.html
    image: futura.png
  - url: https://academia.crandi.com/redes-sociales/scribbn
    image: crandi.png
  - url: https://www.trecebits.com/2022/02/28/scribbn-la-app-que-convierte-a-texto-los-mensajes-de-voz-de-whatsapp
    image: trecebits.png
  - url: https://applicantes.com/scribbn-transcribir-audios-whatsapp-texto
    image: applicantes.png
  - url: https://www.computer-wd.com/2022/01/apps-of-the-week-android-iphone.html
    image: computer-wd.png